### ISSUE TITLE
[mobileOSS] Please release complete kernel source

### ISSUE THREAD

**Issue by TracyWind** [vivo/vivo.github.io#3]
Hello, dear VIVO Engineers. Sorry to disturb you in your busy schedule. **Maybe you would say go to "opensource.vivo.com" to report, but there is no "feedback" option, and the "mobileOSS@vivo.com" doesn't reply to my emails.**

I am an user of the VIVO Y72_5G(PD2069F) from France, its kernel source published on the "opensource.vivo.com" is incomplete. After endlessly checking, I find kernel sources of "Y21s, Y3s, Y81, Y53s, Y72_5G and Y33" are all broken one, with the "power, charger, rtc" drivers deleted. **More precisely, the "drivers/power/supply/vivo" dir is deleted. Obviously, this violates regulations of GPL License applied by Linux Kernel, the "AS IS" requirement.**

Please releasing complete kernel source for these devices. **OpenSource Compliance is never a drama, if dear VIVO really wanna embrace OpenSource, make this possible.**

**Comment by DavidWithTuxedo** [comment]
I don't know if you will succeed, Good Luck you anyway! @TracyWind 
However, please notice that It's not a good idea for you to give feedback here, there are only **front-end engineers**.

Seemly it is your only option, compared with that "not any reply" mailbox.

**Comment by DavidWithTuxedo** [comment]
@TracyWind Please notice that It's not a good idea for you to give feedback here, there are only front-end engineers.

But seemly it is your only option, compared with that "not any reply" mailbox.

**Comment by naveensingh** [comment]
Just here to voice my opinion that I absolutely agree with @TracyWind and @DavidWithTuxedo 

Please publish the whole source code. And maybe do it here on GitHub rather than on an external no-one-knows-kind-website

**Emails**

I once sent a long email requesting the kernel sources best I possibly could and haven't heard from the team. I think nobody's really at home. This must change.

**Comment by MCredbear** [comment]
经济利益不是你们不发布完整内核源码的借口，请发布完整源码，谢谢。

Financial profit is not reasonable for not releasing a complete kernel source, please release a complete kernel source.

**Comment by TracyWind** [comment]
The list has been updated. These models may also be victims.
V21_5G V23_5G
Y76_5G IQOO_Z1

How to test if your device is included?
```bash
# Download the OTA Package for your device  
# Unpack boot.img from it 
# Using tool like abootimg to extract the zImage
$ 7z x zImage
# Decompress the zImage using "7z", then excute this. 
$ strings zImage~ | grep drivers/power/supply/vivo
# Then the list of missing drivers will show up.

**Comment by DavidWithTuxedo** [comment]
> The list has been updated. These models may also be victims. V21_5G V23_5G Y76_5G IQOO_Z1
> 
Let's do some simple calculations. Kernel sources for at least 11 devices are known to be broken, and there are source packs for 26 devices in total on the "opensource.vivo.com".
```bash
Y21s Y33 Y33s Y3s Y53s Y72_5G Y81 V21_5G V23_5G Y76_5G IQOO_Z1
```

The failure rate is approximately 40%.

**Comment by TracyWind** [comment]
@Naveen3Singh @MCredbear @DavidWithTuxedo 
Hi Guys, Maybe I have found the reason why they deleted it.
```bash
CONFIG_VIVO_BQ25890H_FAST_CHARGING=y
# CONFIG_VIVO_BQ2589x_SLAVE_CHARGING is not set
# CONFIG_VIVO_BQ24296_NORMAL_CHARGING is not set
# CONFIG_VIVO_BQ24157_NORMAL_CHARGING is not set
# CONFIG_VIVO_ADAPATOR_5V16A is not set
CONFIG_VIVO_ADAPATOR_5V1A=y
CONFIG_VIVO_HAVE_NO_USBOE=y
```
Look at the "5V16A" text, I guess there are fast-charging drivers in the "drivers/power/supply/vivo" directory, they don't want to disclose it, so they just deleted whole directory.

**Comment by TracyWind** [comment]
@node @labs2020 
Hello, Dear Engineers. Although according to previous issues, you are not responsible for kernel OpenSource. But this is the only official account of VIVO company on github.
Could you please help let the "kernel team" know this?

I would like to speak my mind here too,
1. Users just want manufacturers to abide by the GPL license, we all know you definitely have heavy workloads;
2. Although the "mobileOSS@vivo.com" doesn't reply, users still don't want to send them too many emails with many different mail addresses;
3. I'm not sticking with the old device and I'm looking forward to the release of the x80pro on European market

**Comment by node** [comment]
hi @TracyWind , x80_pro has be released by https://opensource.vivo.com/ on May 25, 2022  . Thanks for your feedback .

**Comment by TracyWind** [comment]
> hi @TracyWind , x80_pro has be released by https://opensource.vivo.com/ on May 25, 2022 . Thanks for your feedback .

@node
Sorry for my ambiguous statement, what I'm waiting for is the release of Y80_PRO on the European market. Dear Engineer, hope you can have a look at the whole issue.

The subject is: 
KernelSource of Y72_5G published on "opensource.vivo.com" is incomplete

My request here:
Could you please contact the kernel team and ask them to re-release the Y72_5G kernel source with the "drivers/power/supply/vivo" folder?

**Comment by TracyWind** [comment]
Eternally waiting here :-) .
If I remember correctly, solutions for last similar issue came about three months after submission, may I'll also have to wait at least three months. 

But I think it's worth, at least with a solution.

**Comment by TracyWind** [comment]
> > The list has been updated. These models may also be victims. V21_5G V23_5G Y76_5G IQOO_Z1
> 
> Let's do some simple calculations. Kernel sources for at least 11 devices are known to be broken, and there are source packs for 26 devices in total on the "opensource.vivo.com".
> 
> ```shell
> Y21s Y33 Y33s Y3s Y53s Y72_5G Y81 V21_5G V23_5G Y76_5G IQOO_Z1
> ```
> 
> The failure rate is approximately 40%.

Objectively, Dear VIVO is supposed to take this problem into consideration.

Someone may ridicule that nearly half of the source pack published on VIVO-OpenSource is unavailable, which finally will damage the image of VIVO.

**Comment by TracyWind** [comment]
@node It's been one week.
Dear Engineer, is there any progress? Even only remind the "Kernel Team" to check the "mobileOSS@vivo.com" mailbox.

**Comment by TracyWind** [comment]
> > @node It's been one week. Dear Engineer, is there any progress? Even only remind the "Kernel Team" to check the "[mobileOSS@vivo.com](mailto:mobileOSS@vivo.com)" mailbox.
> 
> Well, Bro, today seems to be the Dragon Boat Festival in China, engineers may be on vacation.

Thx! @DavidWithTuxedo
I got it, mutual understanding is always essential for problem solving. I'll continue to wait patiently.

**Comment by TracyWind** [comment]
@node Dear Engineer, recently I consulted an engineer friend, and he told me that there may be VIVO's private charging protocol in the "drivers/power/supply/vivo" directory.
Frankly, users are not interested in this private code, "Kernel-Team" can remove those parts, not all of them.

**Comment by TracyWind** [comment]
@Node Dear engineer, bump plz? Is there any good news?

(Digression...) It would be nice if the kernel team of VIVO could join github. Recently one of your competitors, the OnePlus, has also been in the OpenSource turmoil, maybe you could take this chance to demonstrate your OpenSource spirit.
